_target_: fieldspacenn.src.models.mg_diffusion.pl_mg_diffusion_model.LightningMGDiffusionModel
lambda_loss_dict:
  zooms:
    3:
      MSE_loss: 1
    5:
      MSE_loss: 1
    6:
      MSE_loss: 1
weight_decay: 0
lr_groups:
  default:
    lr: 0.001
    warmup: 2000
block_loss_weights: null
model:
  _target_: fieldspacenn.src.models.mg_diffusion.mg_diffusion_model.MGDiffusionModel
  n_blocks: 10
  block_step_ranges:
    - [0, 99]
    - [100, 199]
    - [200, 299]
    - [300, 399]
    - [400, 499]
    - [500, 599]
    - [600, 699]
    - [700, 799]
    - [800, 899]
    - [900, 999]
  inference_step_ranges: null
  pretrained_block_ckpt_path: /home/joe/PycharmProjects/stableclimgen/snapshots/test/mg_transformer/last.ckpt
  mgrids: ${mgrids}
  in_zooms: [3, 5, 6]
  in_features: 1
  out_features: 1
  lift_features: 1
  n_head_channels: 16
  use_mask: false
  n_groups_variables: [2]
  layer_confs_emb:
    aggregation: shift_scale
  block_configs:
    "0":
      _target_: fieldspacenn.src.modules.field_space.field_space_attention.FieldSpaceAttentionConfig
      separate_mlp_norm: true
      q_zooms: [3, 5, 6]
      kv_zooms: [3, 5, 6]
      token_zoom: 3
      att_dim: 32
      token_len_depth: [1, 5]
      token_len_time: 1
      token_overlap_space: true
      token_overlap_time: false
      token_overlap_depth: false
      mlp_token_overlap_time: false
      mlp_token_overlap_depth: false
      rank_depth: [null, 4]
      seq_len_zoom: -1
      seq_len_time: -1
      seq_len_depth: -1
      with_var_att: true
      update: shift
      embed_confs:
        embed_names: ["TimeEmbedder"]
        input_zoom: 3
        embed_confs: ${embedding}
        embed_mode: sum
    "conservative":
      _target_: fieldspacenn.src.modules.field_space.field_space_base.ConservativeLayerConfig
gaussian_diffusion:
  _target_: fieldspacenn.src.modules.diffusion.mg_respace.SpacedDiffusion
  diffusion_steps: 1000
  diffusion_step_scheduler:
    6: linear
    5: linear
    3: linear
  separate_noise_on_zoom: false
