_target_: fieldspacenn.src.models.mg_flowmatching.pl_mg_flowmatching_model.LightningMGFlowMatchingModel
lambda_loss_dict:
  zooms:
    4:
      MSE_loss: 1
    6:
      MSE_loss: 1
    8:
      MSE_loss: 1
weight_decay: 0
lr_groups:
  default:
    lr: 0.001
    warmup: 2000
sampler: euler
sampling_steps_per_block: 1000
block_loss_weights: null
model:
  _target_: fieldspacenn.src.models.mg_flowmatching.mg_flowmatching_model.MGFlowMatchingModel
  n_blocks: 10
  block_time_ranges:
  - - 0.0
    - 0.1
  - - 0.1
    - 0.2
  - - 0.2
    - 0.3
  - - 0.3
    - 0.4
  - - 0.4
    - 0.5
  - - 0.5
    - 0.6
  - - 0.6
    - 0.7
  - - 0.7
    - 0.8
  - - 0.8
    - 0.9
  - - 0.9
    - 1.0
  inference_time_ranges: null
  pretrained_block_ckpt_path: /work/bd1560/k204233/FieldSpaceNN/snapshots/mg_flowmatching_pr/newarch_sr/last.ckpt
  mgrids: ${mgrids}
  in_zooms: [4, 6, 8]
  in_features: 1
  out_features: 1
  lift_features: 1
  n_head_channels: 32
  use_mask: false
  n_groups_variables: [1]
  layer_confs_emb:
    aggregation: shift_scale
  block_configs:
    "0":
      _target_: fieldspacenn.src.modules.field_space.field_space_attention.FieldSpaceAttentionConfig
      separate_mlp_norm: true
      q_zooms: [4, 6, 8]
      kv_zooms: [4, 6, 8]
      token_zoom: 4
      att_dim: 256
      token_len_time: 1
      token_overlap_space: true
      token_overlap_time: false
      token_overlap_depth: false
      mlp_token_overlap_time: false
      mlp_token_overlap_depth: false
      seq_len_zoom: 2
      seq_len_time: -1
      seq_len_depth: -1
      seq_overlap_space: true
      with_var_att: false
      update: shift_scale
      embed_confs:
        embed_names: ["DiffusionStepEmbedder", "TimeEmbedder", "MGEmbedder"]
        input_zoom: 4
        embed_confs: ${embedding}
        embed_mode: sum
    "1":
      _target_: fieldspacenn.src.modules.field_space.field_space_attention.FieldSpaceAttentionConfig
      separate_mlp_norm: true
      q_zooms: [4, 6, 8]
      kv_zooms: [4, 6, 8]
      token_zoom: 4
      att_dim: 256
      token_len_time: 1
      token_overlap_space: true
      token_overlap_time: false
      token_overlap_depth: false
      mlp_token_overlap_time: false
      mlp_token_overlap_depth: false
      seq_len_zoom: 2
      seq_len_time: -1
      seq_len_depth: -1
      seq_overlap_space: true
      with_var_att: false
      update: shift_scale
      embed_confs:
        embed_names: ["DiffusionStepEmbedder", "TimeEmbedder", "MGEmbedder"]
        input_zoom: 4
        embed_confs: ${embedding}
        embed_mode: sum
flow_matching:
  _target_: fieldspacenn.src.modules.flowmatching.mg_flow_matching.MGFlowMatching
  time_embed_key: DiffusionStepEmbedder
  separate_noise_on_zoom: true
  interpolation_mode: linear
